#!/usr/bin/env python3
"""
Self-host the four web fonts so the marketing page makes ZERO external requests
(it pitches air-gapped; the page must prove it). Fetches Google's own woff2
subsets, keeps latin + latin-ext only (English page), rewrites src to local
paths, and writes fonts.css. Re-runnable.
"""
import re, urllib.request, pathlib

CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Archivo:wght@600;700;800;900"
           "&family=IBM+Plex+Mono:wght@400;500;600"
           "&family=Instrument+Serif:ital@0;1"
           "&family=Inter:wght@400;450;500;600;700&display=swap")
# A modern Chrome UA makes Google serve woff2 (not ttf).
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
KEEP = {"latin", "latin-ext"}        # drop cyrillic/greek/vietnamese
HERE = pathlib.Path(__file__).resolve().parent


def fetch(url, ua=UA):
    req = urllib.request.Request(url, headers={"User-Agent": ua} if ua else {})
    return urllib.request.urlopen(req, timeout=30).read()


def main():
    css = fetch(CSS_URL).decode("utf-8")
    blocks = re.split(r"(?=/\*\s*[a-z-]+\s*\*/)", css)   # split on subset comments
    out, files = [], 0
    for blk in blocks:
        m_sub = re.match(r"/\*\s*([a-z-]+)\s*\*/", blk.strip())
        if not m_sub:
            continue
        subset = m_sub.group(1)
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", blk).group(1)
        style = (re.search(r"font-style:\s*(\w+)", blk) or [None, "normal"])[1]
        weight = (re.search(r"font-weight:\s*(\d+)", blk) or [None, "400"])[1]
        url = re.search(r"url\((https://[^)]+\.woff2)\)", blk).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", blk).group(1).strip()
        slug = re.sub(r"[^a-z0-9]+", "-", fam.lower()).strip("-")
        sty = "italic" if style == "italic" else "normal"
        fn = f"{slug}-{weight}-{sty}-{subset}.woff2"
        (HERE / fn).write_bytes(fetch(url, ua=None))
        files += 1
        out.append(
            "@font-face{\n"
            f"  font-family:'{fam}';\n"
            f"  font-style:{style};\n"
            f"  font-weight:{weight};\n"
            "  font-display:swap;\n"
            f"  src:url(./{fn}) format('woff2');\n"
            f"  unicode-range:{urange};\n"
            "}")
    header = ("/* Self-hosted fonts — generated by _fetch_fonts.py. ZERO external\n"
              "   requests at runtime; the page proves the air-gap claim. */\n")
    (HERE / "fonts.css").write_text(header + "\n".join(out) + "\n", encoding="utf-8")
    print(f"downloaded {files} woff2 files; wrote fonts.css ({len(out)} @font-face)")


if __name__ == "__main__":
    main()
